### ISSUE TITLE
Version bump needed?

### ISSUE THREAD

**Issue by narimiran** [yglukhov/ttf#11]
This package is a dependency for `nimx`, which is part of Nim's test suite.
The latest PR (https://github.com/yglukhov/ttf/pull/10) fixed a deprecated (and soon to be removed) `.. <`, but `nimx` seems to pull the latest tagged version which is 0.2.11 and it doesn't contain the mentioned fix.
I think that bumping a version to 0.2.12 would make `nimx` pull the latest changes, and it would pass our tests.

**Comment by yglukhov** [comment]
done
