### ISSUE TITLE
Build failure on Windows.

### ISSUE THREAD

**Issue by jaccarmac** [yglukhov/ttf#5]
This is largely a follow-up on yglukhov/nimx#109, thought it would be better here than reopened there.

The `memory.h` failure is very much present on Windows. As far as I can tell, the version of MinGW-32 which `choosenim` installs does not include the header. So I installed MSYS2 manually, but there ran into problems because neither MSYS-bundled version of MinGW agreed with the Nim compiler chain on pointer sizes. So as far as I know the two workarounds are bypassing the buggy line on Windows or installing Nim fully inside MinGW from source.

I tried all this on Windows 7.

**Comment by yglukhov** [comment]
Indeed. choosenim installs an ancient version of mingw, and that should be fixed in choosenim.

**Comment by yglukhov** [comment]
It should be fixed in choosenim iirc
