### ISSUE TITLE
nimble package name doesn't match

### ISSUE THREAD

**Issue by timotheecour** [yglukhov/ttf#9]
```
nimble develop ttf
    Prompt: ttf not found in any local packages.json, check internet for updated packages? [y/N]
```

```
nimble search ttf
sdl2_nim:
  url:         https://github.com/Vladar4/sdl2_nim (git)
  tags:        library, wrapper, sdl2, game, video, image, audio, network, ttf
  description: Wrapper of the SDL 2 library for the Nim language.
  license:     zlib
  website:     https://github.com/Vladar4/sdl2_nim
```

then there's this:
/Users/timothee/.nimble/pkgs/ttf-0.2.8/ttf.nim
presumably installed as dependency of nimx

I was trying to debug https://github.com/yglukhov/ttf/issues/8 but ran into this naming issue ...

**Comment by yglukhov** [comment]
Well this package is not in the registry. How is that an issue?

**Comment by timotheecour** [comment]
oh, I thought only packages in the registry could end up in ~/.nimble/pkgs ? if that's not the case and local packages can end up (as dependency) in ~/.nimble/pkgs, what prevents name clashes ?  /cc @dom96

**Comment by yglukhov** [comment]
Nothing prevents name clashes. I suppose it's a nim/nimble design issue.

**Comment by dom96** [comment]
Pretty sure this is how most package managers work.

**Comment by yglukhov** [comment]
Pretty sure there is a way to resolve this gracefully ;)

**Comment by dom96** [comment]
Happy to hear your suggestions

**Comment by yglukhov** [comment]
@dom96 The solution can be expressed in the semantics of the nimble file. Instead of `requires "whatever"` introduce a new proc.
```nim
proc req*(name: string, git = "", hg = "", ver = "", branch = "", github = "")
```
Now the nimble file would look like
```nim
req("ttf", github = "yglukhov/ttf")
```
Which would mean that every `import ttf/*` in `this` package would be essentially an import with given github origin. I'll be happy to discuss it in more detail. Feel free to contact me on gitter or telegram :)

**Comment by dom96** [comment]
This is a great idea, but it creates some challenges. The main one is the directory containing Nimble packages, you will need to change its structure and either give up making Nim understand it (which means no `nim c` support for Nimble packages) or implementing special logic into Nim's package resolution logic.

**Comment by yglukhov** [comment]
Well that's why i said "nim/nimble design issue", because thats what it is, isn't it? :)

**Comment by dom96** [comment]
sure, I'm just trying to give the clear picture of what I see as the problems. Anyway, feel free to create an RFC/issue for this so we come up with a fully specified solution.
